#ifndef _BATTLEFIELD_RTS
#define _BATTLEFIELD_RTS

#define FIX_SQUARE 0
#define FIX_HEIGHT 1
#define RED 99
#define BLUE 66
#define MONEYMINE_GOLD 2000
#define WARFACTORY_GOLD 2000
#define SOLDIERBASE_GOLD 500
#define POWERPLANT_GOLD 600
#define MONEYMINE_ELECT 40
#define WARFACTORY_ELECT 50
#define SOLDIERBASE_ELECT 10
#define DOG_SPEED 0.2
#define TANK_SPEED 0.5
#define SOIDIER_SPEED 0.4



#endif // !_BATTLEFIELD_RTS

