// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rts_exchange.proto
#ifndef GRPC_rts_5fexchange_2eproto__INCLUDED
#define GRPC_rts_5fexchange_2eproto__INCLUDED

#include "rts_exchange.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Exchange final {
 public:
  static constexpr char const* service_full_name() {
    return "Exchange";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::GameMessageSet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>> AsyncOneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>>(AsyncOneExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>> PrepareAsyncOneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>>(PrepareAsyncOneExchangeRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>* AsyncOneExchangeRaw(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GameMessageSet>* PrepareAsyncOneExchangeRaw(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status OneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::GameMessageSet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GameMessageSet>> AsyncOneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GameMessageSet>>(AsyncOneExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GameMessageSet>> PrepareAsyncOneExchange(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GameMessageSet>>(PrepareAsyncOneExchangeRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::GameMessageSet>* AsyncOneExchangeRaw(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GameMessageSet>* PrepareAsyncOneExchangeRaw(::grpc::ClientContext* context, const ::GameMessageSet& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OneExchange_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OneExchange(::grpc::ServerContext* context, const ::GameMessageSet* request, ::GameMessageSet* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OneExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_OneExchange() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OneExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneExchange(::grpc::ServerContext* context, const ::GameMessageSet* request, ::GameMessageSet* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOneExchange(::grpc::ServerContext* context, ::GameMessageSet* request, ::grpc::ServerAsyncResponseWriter< ::GameMessageSet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OneExchange<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_OneExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_OneExchange() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OneExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OneExchange(::grpc::ServerContext* context, const ::GameMessageSet* request, ::GameMessageSet* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OneExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_OneExchange() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::GameMessageSet, ::GameMessageSet>(std::bind(&WithStreamedUnaryMethod_OneExchange<BaseClass>::StreamedOneExchange, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_OneExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OneExchange(::grpc::ServerContext* context, const ::GameMessageSet* request, ::GameMessageSet* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOneExchange(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GameMessageSet,::GameMessageSet>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OneExchange<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OneExchange<Service > StreamedService;
};


#endif  // GRPC_rts_5fexchange_2eproto__INCLUDED
